import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { presentationConfig } from '../config/presentation'
import { ConnectionStatus } from '../components/ConnectionStatus'
import { RingMark } from '../components/RingMark'
import { AppShell } from '../components/AppShell'
import { useMotion } from '../motion/MotionProvider'
import './home.css'

const experiences = [{ number: '01', title: 'Motion Input', copy: 'See tilt, direction and intensity become clear visual signals.', to: '/motion-visualizer', icon: '⌁' }, { number: '02', title: 'Kinetic Field', copy: 'Move your hand to push, bend and reorganize a responsive field of particles.', to: '/kinetic-field', icon: '◍' }, { number: '03', title: 'Motion Synth', copy: 'Shape a quiet soundscape with the smallest gesture.', to: '/motion-synthesizer', icon: '≈' }, { number: '04', title: '3D Viewer', copy: 'Turn a product showcase with a natural hand roll.', to: '/product-viewer', icon: '◇' }, { number: '05', title: 'Spatial Gallery', copy: 'Navigate a spatial collection by moving in four directions.', to: '/orbital-balance', icon: '▦' }]
export function HomePage() { const { useDemoMode } = useMotion(); return <AppShell><main className="home"><nav><Link to="/" className="brand"><span />Beyond the Tap</Link><ConnectionStatus /></nav><section className="hero"><div className="hero-copy"><p className="eyebrow">{presentationConfig.eyebrow}</p><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}>{presentationConfig.title}</motion.h1><p className="subtitle">{presentationConfig.subtitle}</p><p className="intro">A small experiment in the space beyond taps, swipes, and screens. Motion becomes a quiet, expressive controller.</p><div className="actions"><button className="button muted" onClick={useDemoMode}>Use Demo Mode</button><Link className="button" to="/motion-visualizer">Explore motion <span>→</span></Link></div><Link className="motion-link" to="/motion-visualizer">See how motion works →</Link></div><div className="hero-object"><RingMark /><p>Motion-first interface<br /><i>01 — 05</i></p></div></section><section className="experience-list"><div className="section-intro"><p className="eyebrow">Five studies</p><p>Choose an experience. Every scene responds to the same dependable demo input or your live Oura Ring.</p></div><div className="cards">{experiences.map((item, index) => <motion.article className="experience-card" key={item.title} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 + index * .1 }}><span>{item.number}</span><div className="card-icon">{item.icon}</div><h2>{item.title}</h2><p>{item.copy}</p><Link to={item.to}>Launch <b>↗</b></Link></motion.article>)}</div></section></main></AppShell> }
