import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { presentationConfig } from '../config/presentation'
import { ConnectionStatus } from '../components/ConnectionStatus'
import { RingMark } from '../components/RingMark'
import { useMotion } from '../motion/MotionProvider'

const experiences = [{ number: '01', title: 'Spatial Gallery', copy: 'Navigate a spatial collection by moving in four directions.', to: '/orbital-balance', icon: '✦' }, { number: '02', title: 'Motion Synthesizer', copy: 'Shape a quiet soundscape with the smallest gesture.', to: '/motion-synthesizer', icon: '⌁' }, { number: '03', title: '3D Product Viewer', copy: 'Turn a product showcase with a natural hand roll.', to: '/product-viewer', icon: '◌' }]
export function HomePage() { const { useDemoMode } = useMotion(); return <main className="home"><nav><Link to="/" className="brand"><span />BT</Link><ConnectionStatus /></nav><section className="hero"><div className="hero-copy"><p className="eyebrow">{presentationConfig.eyebrow}</p><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}>{presentationConfig.title}</motion.h1><p className="subtitle">{presentationConfig.subtitle}</p><p className="intro">A small experiment in the space beyond taps, swipes, and screens. Motion becomes a quiet, expressive controller.</p><div className="actions"><button className="button muted" disabled title="Bluetooth is intentionally outside this first increment">Connect Oura Ring</button><button className="button" onClick={useDemoMode}>Use Demo Mode <span>→</span></button></div><Link className="motion-link" to="/motion-visualizer">See how motion works →</Link></div><div className="hero-object"><RingMark /><p>Motion-first interface<br /><i>01 — 03</i></p></div></section><section className="experience-list"><div className="section-intro"><p className="eyebrow">Three studies</p><p>Choose an experience. Every scene responds to the same dependable demo input.</p></div><div className="cards">{experiences.map((item, index) => <motion.article className="experience-card" key={item.title} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 + index * .1 }}><span>{item.number}</span><div className="card-icon">{item.icon}</div><h2>{item.title}</h2><p>{item.copy}</p><Link to={item.to}>Launch <b>↗</b></Link></motion.article>)}</div></section></main> }
