export type Vec3 = [number, number, number]
export type OuraMotionSettings = { invertHorizontal: boolean; invertVertical: boolean; swapAxes: boolean; deadZoneDegrees: number; fullScaleDegrees: number; smoothing: number; countsPerG: number }
export type OrientationBasis = { neutral: Vec3; horizontal: Vec3; vertical: Vec3 }
export const defaultOuraSettings: OuraMotionSettings = { invertHorizontal: false, invertVertical: false, swapAxes: false, deadZoneDegrees: 3, fullScaleDegrees: 28, smoothing: .18, countsPerG: 1000 }
export const clampOura = (value: number, min = -1, max = 1) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : 0))
export const dot = (a: Vec3, b: Vec3) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
export const cross = (a: Vec3, b: Vec3): Vec3 => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]]
export const magnitude = (value: Vec3) => Math.hypot(...value)
export const normalizeVector = (value: Vec3): Vec3 | null => { const length = magnitude(value); return length > .0001 && Number.isFinite(length) ? [value[0] / length, value[1] / length, value[2] / length] : null }
export const averageNormalized = (samples: Vec3[]): Vec3 | null => { if (!samples.length) return null; const sum = samples.reduce<Vec3>((result, sample) => [result[0] + sample[0], result[1] + sample[1], result[2] + sample[2]], [0, 0, 0]); return normalizeVector(sum) }
export function createOrientationBasis(neutral: Vec3): OrientationBasis { const seed: Vec3 = Math.abs(dot([1, 0, 0], neutral)) < .9 ? [1, 0, 0] : [0, 0, 1]; const projected: Vec3 = [seed[0] - neutral[0] * dot(seed, neutral), seed[1] - neutral[1] * dot(seed, neutral), seed[2] - neutral[2] * dot(seed, neutral)]; const horizontal = normalizeVector(projected) ?? [1, 0, 0]; return { neutral, horizontal, vertical: normalizeVector(cross(neutral, horizontal)) ?? [0, 1, 0] } }
export const normalizeAxis = (degrees: number, deadZoneDegrees: number, fullScaleDegrees: number) => { const size = Math.abs(degrees); if (size <= deadZoneDegrees) return 0; return clampOura(Math.sign(degrees) * (size - deadZoneDegrees) / Math.max(1, fullScaleDegrees - deadZoneDegrees)) }
export function deriveTilt(sample: Vec3, basis: OrientationBasis, settings: OuraMotionSettings) { const unit = normalizeVector(sample); if (!unit) return { horizontalDegrees: 0, verticalDegrees: 0, horizontal: 0, vertical: 0 }; const horizontalDegrees = Math.asin(clampOura(dot(unit, basis.horizontal))) * 180 / Math.PI; const verticalDegrees = Math.asin(clampOura(dot(unit, basis.vertical))) * 180 / Math.PI; let horizontal = normalizeAxis(horizontalDegrees, settings.deadZoneDegrees, settings.fullScaleDegrees); let vertical = normalizeAxis(verticalDegrees, settings.deadZoneDegrees, settings.fullScaleDegrees); if (settings.swapAxes) [horizontal, vertical] = [vertical, horizontal]; if (settings.invertHorizontal) horizontal *= -1; if (settings.invertVertical) vertical *= -1; return { horizontalDegrees, verticalDegrees, horizontal, vertical }
}
