import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { spawn, spawnSync } from 'node:child_process'

const root = process.cwd(); const localEnv = resolve(root, '.env.oura'); if (existsSync(localEnv)) for (const line of readFileSync(localEnv, 'utf8').split(/\r?\n/)) { const match = line.match(/^\s*([A-Z0-9_]+)=(.*)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, '') }; const env = process.env; const repo = env.OPEN_OURA_DIR || resolve(root, '.tools/open_oura'); const binary = resolve(repo, 'target/release/oura'); const keyFile = env.OURA_KEY_FILE; const ringName = env.OURA_RING_NAME || 'Oura'; const port = env.OURA_SERVER_PORT || '8088'; const minutes = env.OURA_STREAM_MINUTES || '15'
const run = (command, args, options = {}) => spawnSync(command, args, { cwd: repo, stdio: 'inherit', env, ...options }).status ?? 1
const requireBinary = () => { if (!existsSync(binary)) { console.error('open_oura is not built. Run: pnpm oura:setup'); process.exit(1) } }
const withKey = args => { if (!keyFile) { console.error('Set OURA_KEY_FILE to a secure local 16-byte key-file path in .env.oura.'); process.exit(1) } return ['--name', ringName, '--key-file', keyFile, ...args] }
const command = process.argv[2]
if (command === 'setup') { if (!existsSync(repo)) { const parent = resolve(repo, '..'); const made = spawnSync('mkdir', ['-p', parent], { stdio: 'inherit' }); if (made.status) process.exit(made.status); const cloned = spawnSync('git', ['clone', 'https://github.com/Th0rgal/open_oura.git', repo], { stdio: 'inherit' }); if (cloned.status) process.exit(cloned.status) } const revision = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: repo, encoding: 'utf8' }); if (!revision.status) console.log(`open_oura revision: ${revision.stdout.trim()}`); process.exit(run('cargo', ['build', '--release'])) }
if (command === 'scan') { requireBinary(); process.exit(run(binary, ['scan'])) }
if (command === 'pair') { requireBinary(); if (env.OURA_CONFIRM_PAIR !== '1') { console.error('Pairing writes an auth key. Manually factory-reset the dedicated backup ring first, then rerun with OURA_CONFIRM_PAIR=1.'); process.exit(1) } if (!keyFile) { console.error('Set OURA_KEY_FILE outside the repository before pairing.'); process.exit(1) } if (existsSync(keyFile)) { console.error('Refusing to overwrite or re-install an existing key file. Choose a new path deliberately.'); process.exit(1) } process.exit(run(binary, withKey(['pair']))) }
if (command === 'verify') { requireBinary(); if (run(binary, withKey(['info']))) process.exit(1); process.exit(run(binary, withKey(['accel', '--seconds', '15']))) }
if (command === 'serve') { requireBinary(); process.exit(run(binary, withKey(['viz', '--port', port, '--minutes', minutes]))) }
if (command === 'live') { const web = spawn('pnpm', ['dev'], { stdio: 'inherit', env }); const bridge = spawn('node', ['scripts/oura.mjs', 'serve'], { stdio: 'inherit', env }); bridge.on('exit', code => console.error(`[oura] bridge exited (${code ?? 'unknown'}); React remains available in Demo Mode.`)); const stop = () => { web.kill('SIGINT'); bridge.kill('SIGINT') }; process.on('SIGINT', stop); process.on('SIGTERM', stop); web.on('exit', code => process.exit(code ?? 0)); }
console.error('Usage: pnpm oura:{setup|scan|pair|verify|serve} or pnpm dev:live'); process.exit(1)
